### ISSUE TITLE
Gem inclusion does not work

### ISSUE THREAD

**Issue by cmdrkeene** [daveworth/Indirizzo#8]
First off, naming this with a capital "I" defies most convention and I am frowning upon it.

Second, this gem doesn't work.

Installing the gem works OK, but it's unusable.

`require 'Indirizzo'` does not work.

lower case also does not work:

`require 'indirizzo'`
`LoadError: cannot load such file -- indirizzo`

And as some have suggested, including the useful `Address` class directly also doesn't work:
`require 'indirizzo/address'
LoadError: cannot load such file -- indirizzo/constants`

Someone with a working knowledge of proper Gem creation should be able to fix this. Really sad to see potentially useful but likely malformed and abandoned gems out there. Kudos if someone helps. I can't waste my time on broken stuff for that long, as I have to move on and solve my actual problem.

Thanks for getting this code almost there.

**Comment by baburdick** [comment]
@cmdrkeene: See https://github.com/HornsAndHooves/indirizzo for a conventionally-named fork.

**Comment by cmdrkeene** [comment]
Awesome thanks @baburdick !
